services:
  - type: web
    name: college-course-review
    env: static
    buildCommand: npm install --legacy-peer-deps && NODE_OPTIONS=--openssl-legacy-provider npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 